services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-80}:80"
      - "${APP_PORT:-443}:443"
    env_file:
      - .env
    depends_on:
      - db
    networks:
        - default
  db:
    image: mariadb:latest
    restart: always
    env_file: ".env"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  mariadb_data:

networks:
  default:
