CREATE
DATABASE IF NOT EXISTS schema_a;
CREATE
DATABASE IF NOT EXISTS schema_b;

USE schema_a;

CREATE TABLE `tblclients`
(
    `id`                      int(10) NOT NULL AUTO_INCREMENT,
    `uuid`                    varchar(255)   NOT NULL DEFAULT '',
    `firstname`               text           NOT NULL,
    `lastname`                text           NOT NULL,
    `companyname`             text           NOT NULL,
    `email`                   text           NOT NULL,
    `address1`                text           NOT NULL,
    `address2`                text           NOT NULL,
    `city`                    text           NOT NULL,
    `state`                   text           NOT NULL,
    `postcode`                text           NOT NULL,
    `country`                 text           NOT NULL,
    `phonenumber`             text           NOT NULL,
    `tax_id`                  varchar(128)   NOT NULL DEFAULT '',
    `password`                text           NOT NULL,
    `authmodule`              text           NOT NULL,
    `authdata`                text           NOT NULL,
    `currency`                int(10) NOT NULL,
    `defaultgateway`          text           NOT NULL,
    `credit`                  decimal(16, 2) NOT NULL,
    `taxexempt`               tinyint(1) NOT NULL,
    `latefeeoveride`          tinyint(1) NOT NULL,
    `overideduenotices`       tinyint(1) NOT NULL,
    `separateinvoices`        tinyint(1) NOT NULL,
    `disableautocc`           tinyint(1) NOT NULL,
    `datecreated`             date           NOT NULL,
    `notes`                   text           NOT NULL,
    `billingcid`              int(10) NOT NULL,
    `securityqid`             int(10) NOT NULL,
    `securityqans`            text           NOT NULL,
    `groupid`                 int(10) NOT NULL,
    `cardtype`                varchar(255)   NOT NULL DEFAULT '',
    `cardlastfour`            text           NOT NULL,
    `cardnum`                 blob           NOT NULL,
    `startdate`               blob           NOT NULL,
    `expdate`                 blob           NOT NULL,
    `issuenumber`             blob           NOT NULL,
    `bankname`                text           NOT NULL,
    `banktype`                text           NOT NULL,
    `bankcode`                blob           NOT NULL,
    `bankacct`                blob           NOT NULL,
    `gatewayid`               text           NOT NULL,
    `lastlogin`               datetime                DEFAULT NULL,
    `ip`                      text           NOT NULL,
    `host`                    text           NOT NULL,
    `status`                  enum('Active','Inactive','Closed') NOT NULL DEFAULT 'Active',
    `language`                text           NOT NULL,
    `pwresetkey`              text           NOT NULL,
    `emailoptout`             int(1) NOT NULL,
    `marketing_emails_opt_in` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `overrideautoclose`       int(1) NOT NULL,
    `allow_sso`               tinyint(1) NOT NULL DEFAULT 1,
    `email_verified`          tinyint(1) NOT NULL DEFAULT 0,
    `email_preferences`       text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
    `created_at`              timestamp      NOT NULL DEFAULT '0000-00-00 00:00:00',
    `updated_at`              timestamp      NOT NULL DEFAULT '0000-00-00 00:00:00',
    `pwresetexpiry`           timestamp      NOT NULL DEFAULT '0000-00-00 00:00:00',
    PRIMARY KEY (`id`),
    KEY                       `firstname_lastname` (`firstname`(32),`lastname`(32)),
    KEY                       `email` (`email`(64)),
    KEY                       `client_status_id` (`status`,`id`),
    KEY                       `lastlogin` (`lastlogin`)
) ENGINE=InnoDB AUTO_INCREMENT=8750 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `tblusers`
(
    `id`                              int(10) unsigned NOT NULL AUTO_INCREMENT,
    `first_name`                      varchar(255) NOT NULL DEFAULT '',
    `last_name`                       varchar(255) NOT NULL DEFAULT '',
    `email`                           varchar(255) NOT NULL DEFAULT '',
    `password`                        varchar(255) NOT NULL DEFAULT '',
    `language`                        varchar(32)  NOT NULL DEFAULT '',
    `second_factor`                   varchar(255) NOT NULL DEFAULT '',
    `second_factor_config`            text                  DEFAULT NULL,
    `remember_token`                  varchar(100) NOT NULL DEFAULT '',
    `reset_token`                     varchar(255) NOT NULL DEFAULT '',
    `security_question_id`            int(10) unsigned NOT NULL DEFAULT 0,
    `security_question_answer`        varchar(255) NOT NULL DEFAULT '',
    `last_ip`                         varchar(64)  NOT NULL DEFAULT '',
    `last_hostname`                   varchar(255) NOT NULL DEFAULT '',
    `last_login`                      timestamp NULL DEFAULT NULL,
    `email_verification_token`        varchar(100) NOT NULL DEFAULT '',
    `email_verification_token_expiry` timestamp NULL DEFAULT NULL,
    `email_verified_at`               timestamp NULL DEFAULT NULL,
    `reset_token_expiry`              timestamp NULL DEFAULT NULL,
    `created_at`                      timestamp NULL DEFAULT NULL,
    `updated_at`                      timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `tblusers_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=18080 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

CREATE TABLE `tblusers_clients`
(
    `id`           int(10) unsigned NOT NULL AUTO_INCREMENT,
    `auth_user_id` int(10) unsigned NOT NULL DEFAULT 0,
    `client_id`    int(10) unsigned NOT NULL DEFAULT 0,
    `invite_id`    int(10) unsigned NOT NULL DEFAULT 0,
    `owner`        tinyint(3) unsigned NOT NULL DEFAULT 0,
    `permissions`  text DEFAULT NULL,
    `last_login`   timestamp NULL DEFAULT NULL,
    `created_at`   timestamp NULL DEFAULT NULL,
    `updated_at`   timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `user_id_client_id` (`auth_user_id`,`client_id`),
    KEY            `client_id_owner_idx` (`client_id`,`owner`)
) ENGINE=InnoDB AUTO_INCREMENT=18184 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

USE     schema_b;

CREATE TABLE `tblclients`
(
    `id`                      int(10) NOT NULL AUTO_INCREMENT,
    `uuid`                    varchar(255)   NOT NULL DEFAULT '',
    `firstname`               text           NOT NULL,
    `lastname`                text           NOT NULL,
    `companyname`             text           NOT NULL,
    `email`                   text           NOT NULL,
    `address1`                text           NOT NULL,
    `address2`                text           NOT NULL,
    `city`                    text           NOT NULL,
    `state`                   text           NOT NULL,
    `postcode`                text           NOT NULL,
    `country`                 text           NOT NULL,
    `phonenumber`             text           NOT NULL,
    `tax_id`                  varchar(128)   NOT NULL DEFAULT '',
    `password`                text           NOT NULL,
    `authmodule`              text           NOT NULL,
    `authdata`                text           NOT NULL,
    `currency`                int(10) NOT NULL,
    `defaultgateway`          text           NOT NULL,
    `credit`                  decimal(16, 2) NOT NULL,
    `taxexempt`               tinyint(1) NOT NULL,
    `latefeeoveride`          tinyint(1) NOT NULL,
    `overideduenotices`       tinyint(1) NOT NULL,
    `separateinvoices`        tinyint(1) NOT NULL,
    `disableautocc`           tinyint(1) NOT NULL,
    `datecreated`             date           NOT NULL,
    `notes`                   text           NOT NULL,
    `billingcid`              int(10) NOT NULL,
    `securityqid`             int(10) NOT NULL,
    `securityqans`            text           NOT NULL,
    `groupid`                 int(10) NOT NULL,
    `cardtype`                varchar(255)   NOT NULL DEFAULT '',
    `cardlastfour`            text           NOT NULL,
    `cardnum`                 blob           NOT NULL,
    `startdate`               blob           NOT NULL,
    `expdate`                 blob           NOT NULL,
    `issuenumber`             blob           NOT NULL,
    `bankname`                text           NOT NULL,
    `banktype`                text           NOT NULL,
    `bankcode`                blob           NOT NULL,
    `bankacct`                blob           NOT NULL,
    `gatewayid`               text           NOT NULL,
    `lastlogin`               datetime                DEFAULT NULL,
    `ip`                      text           NOT NULL,
    `host`                    text           NOT NULL,
    `status`                  enum('Active','Inactive','Closed') NOT NULL DEFAULT 'Active',
    `language`                text           NOT NULL,
    `pwresetkey`              text           NOT NULL,
    `emailoptout`             int(1) NOT NULL,
    `marketing_emails_opt_in` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `overrideautoclose`       int(1) NOT NULL,
    `allow_sso`               tinyint(1) NOT NULL DEFAULT 1,
    `email_verified`          tinyint(1) NOT NULL DEFAULT 0,
    `email_preferences`       text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
    `created_at`              timestamp      NOT NULL DEFAULT '0000-00-00 00:00:00',
    `updated_at`              timestamp      NOT NULL DEFAULT '0000-00-00 00:00:00',
    `pwresetexpiry`           timestamp      NOT NULL DEFAULT '0000-00-00 00:00:00',
    PRIMARY KEY (`id`),
    KEY                       `firstname_lastname` (`firstname`(32),`lastname`(32)),
    KEY                       `email` (`email`(64)),
    KEY                       `client_status_id` (`status`,`id`),
    KEY                       `lastlogin` (`lastlogin`)
) ENGINE=InnoDB AUTO_INCREMENT=16555 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `tblusers`
(
    `id`                              int(10) unsigned NOT NULL AUTO_INCREMENT,
    `first_name`                      varchar(255) NOT NULL DEFAULT '',
    `last_name`                       varchar(255) NOT NULL DEFAULT '',
    `email`                           varchar(255) NOT NULL DEFAULT '',
    `password`                        varchar(255) NOT NULL DEFAULT '',
    `language`                        varchar(32)  NOT NULL DEFAULT '',
    `second_factor`                   varchar(255) NOT NULL DEFAULT '',
    `second_factor_config`            text                  DEFAULT NULL,
    `remember_token`                  varchar(100) NOT NULL DEFAULT '',
    `reset_token`                     varchar(255) NOT NULL DEFAULT '',
    `security_question_id`            int(10) unsigned NOT NULL DEFAULT 0,
    `security_question_answer`        varchar(255) NOT NULL DEFAULT '',
    `last_ip`                         varchar(64)  NOT NULL DEFAULT '',
    `last_hostname`                   varchar(255) NOT NULL DEFAULT '',
    `last_login`                      timestamp NULL DEFAULT NULL,
    `email_verification_token`        varchar(100) NOT NULL DEFAULT '',
    `email_verification_token_expiry` timestamp NULL DEFAULT NULL,
    `email_verified_at`               timestamp NULL DEFAULT NULL,
    `reset_token_expiry`              timestamp NULL DEFAULT NULL,
    `created_at`                      timestamp NULL DEFAULT NULL,
    `updated_at`                      timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `tblusers_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=36127 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

CREATE TABLE `tblusers_clients`
(
    `id`           int(10) unsigned NOT NULL AUTO_INCREMENT,
    `auth_user_id` int(10) unsigned NOT NULL DEFAULT 0,
    `client_id`    int(10) unsigned NOT NULL DEFAULT 0,
    `invite_id`    int(10) unsigned NOT NULL DEFAULT 0,
    `owner`        tinyint(3) unsigned NOT NULL DEFAULT 0,
    `permissions`  text DEFAULT NULL,
    `last_login`   timestamp NULL DEFAULT NULL,
    `created_at`   timestamp NULL DEFAULT NULL,
    `updated_at`   timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `user_id_client_id` (`auth_user_id`,`client_id`),
    KEY            `client_id_owner_idx` (`client_id`,`owner`)
) ENGINE=InnoDB AUTO_INCREMENT=36142 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

